include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude: ['**/*.freezed.dart', '**/*.g.dart']

linter:
  rules:
    public_member_api_docs: false
    always_put_control_body_on_new_line: true
